model_name: JsonHttpActionModel
config:
  adapter_class_name: JsonHttpAdapter
  headers:
    format: yaml
    template: |
      Content-Type: application/json
      x-api-key: [[ globals.x_api_key ]]
  method:
    format: string
    template: GET
  url:
    format: string
    template: "[[ globals.base_url ]]/categories"
description: Get Cat Categories
[% if actions.get_categories.execution_id is defined %]
execution_id: [[ actions.get_categories.execution_id ]]
[% endif %]
schemas:
  - id: "200"
    model_name: JsonSchemaModel
    schema_ :
      format: yaml
      text: |
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
          required:
            - id
            - name
schema_validators:
[% if actions.get_categories.validate_body_200 is defined and actions.get_categories.validate_body_200 is true %]
  - id: "200"
    model_name: JsonSchemaValidatorModel
    schema_id: "200"
    against: 'output_body'
[% endif %]