# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build all formats
formats: all

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  # Specify apt-get install packages
  apt_packages:
    # Required by nbspphinx
    - pandoc
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
   fail_on_warning: false


# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: ".[test]"
   system_packages: true
