compile_folder: build/compiled
run_folder: build/run
action: {}
backend:
  processor: SimpleBackend
discovery:
  functions_folder_path: functions
  manifests_folder_path: manifests
logging:
  event_filters:
    - Specification
    - Scenario
    - Action
    - Assertion
  log_file_path: log.jsonl
  logging_level: 5
  log_format: "%(event)s - %(levelname)s - %(message)s"
env_files:
  default: test
  packs:
  - name: base
    paths:
    - envs/base-env.yaml
  - name: test
    paths:
    - envs/base-env.yaml
    - envs/test-env.yaml
reporting:
  processor: HtmlReport
  reports_folder: build/reports
selectors:
  default: spec
  packs:
  - manifest_file_paths: []
    models:
    - SpecificationModel
    name: spec
    tags: []
    type: Include
  - manifest_file_paths: []
    models:
    - JsonHttpActionModel
    - XmlHttpActionModel
    name: action
    tags: []
    type: Include
