name: Publish Model Schemas to Github Release

description: Publish Model Schemas to GitHub Release
inputs:
  python-version:
    required: true
    description: "The python version to use"
  zip-file-path:
    required: true
    description: "Path of the built artifact as zip"

runs:
  using: "composite"
  steps:
    # Step 1: Build
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[all]"
    - name: Dump Model Schemas
      id: dump-model-schemas
      shell: bash
      run: |
        make output_folder_path=model_schemas dump_model_schemas
    # Step 3: Zip artifact
    - name: zip model schemas artifact
      shell: bash
      run: |
        zip -r ${{ inputs.zip-file-path }} ./model_schemas