version: '3'
services:
  client-notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
  api-server-one:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9999:9999