version: '3'
services:
  client-notebook:
    build:
      context: ..
      dockerfile: ./tutorials/Dockerfile
    volumes:
      - ../src:/home/jovyan/src
      - ../tutorials:/home/jovyan/tutorials
      - ./configs/jupyter_lab_config.py:/home/jovyan/.jupyter/jupyter_lab_config.py
    ports:
      - 8888:8888