name: Run Pytest

description: "Run pytest"
inputs:
  python-version:
    required: true
    description: "The python version to use"
  host:
    required: true
    description: "Host where pytest is run"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Run Setup
      shell: bash
      run: |
        make setup
    - name: Run Pytest - Unit Tests
      shell: bash
      run: |
        make unit_test
    - name: Run Pytest - E2E Tests
      shell: bash
      run: |
        make integration_test
    - name: Archive Build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files-${{ inputs.python-version }}-${{ inputs.host }}
        path: |
          build