model_name: JsonHttpActionModel
description: I cancel all orders
tags:
  - tests
[% if actions.cancel_all_orders.execution_id is defined %]
execution_id: [[ actions.cancel_all_orders.execution_id ]]
[% endif %]
pre_hook_context:
  nonce: [[ actions.cancel_all_orders.nonce| acp.utils.double_quote ]]
  timestamp: [[ actions.cancel_all_orders.timestamp| acp.utils.double_quote ]]
config:
  method:
   template: 'POST'
  url:
   template: "[[ globals.BX_API_BASE_URL ]]/trading-api/v1/command"
   format: 'string'
  headers:
    template: |
      Content-type: "application/json"
      Authorization: "Bearer [[ actions.cancel_all_orders.token ]]"
      BX-SIGNATURE: "[[ actions.cancel_all_orders.signature ]]"
      BX-TIMESTAMP: {{ timestamp | acp.utils.double_quote }}
      BX-NONCE: {{ nonce| acp.utils.double_quote }}
    format: 'yaml'
  body:
    template: |
       timestamp: {{ timestamp | acp.utils.double_quote }}
       nonce: {{ nonce | acp.utils.double_quote }}
       authorizer: "Bearer [[ actions.cancel_all_orders.authorizer ]]"
       command:
        commandType: "V1CancelAllOrders"
        tradingAccountId: [[ actions.cancel_all_orders.trading_account_id| acp.utils.double_quote ]]
    format: 'yaml'
  params:
   template: |
      commandType: V1CancelAllOrders
   format: 'json'





