#!/bin/bash

set -e

pip install -r ./tutorials/requirements.txt
cd ./tutorials/api_server_one

pipenv install --dev && pipenv shell
./app.py # start the HTTP server

echo 'please check http://localhost:8080/ui'
