name: On Commit Push To Main

on:
  push:
    branches:
      - main

jobs:
  pytest:
    permissions: write-all
    strategy:
      matrix:
        python-version:
         - "3.9"
         - "3.10"
         - "3.11"
        hosts:
          - 'windows-latest'
          - 'ubuntu-latest'
          - 'macos-latest'
    runs-on: ${{ matrix.hosts }}
    steps:
      - uses: actions/checkout@v3
      - name: Run Pytest
        id: run-pytest
        uses: ./.github/actions/run-pytest
        with:
          python-version: ${{ matrix.python-version }}

  publish-to-pypi:
    needs:
      - pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if Package already exists on PyPI
        id: check-pypi
        uses: ./.github/actions/check-if-package-exists-on-pypi
        with:
          python-version: "3.10"
      - name: Publish to PyPI
        if: steps.check-pypi.outputs.exists == 'False'
        uses: ./.github/actions/publish-to-pypi
        with:
          pypi-api-token: ${{ secrets.PYPI_API_TOKEN }}
          python-version: "3.10"
